name: E2E test

on:
  workflow_dispatch:

jobs:
  copy-doc-from-template:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # See https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-google-cloud-platform#requesting-the-access-token
    steps:
      - uses: actions/checkout@v3
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: ${{ secrets.E2E_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: '${{ secrets.E2E_SERVICE_ACCOUNT }}'
          token_format: access_token
          access_token_scopes: https://www.googleapis.com/auth/documents,https://www.googleapis.com/auth/drive.file
          access_token_lifetime: 300s
      - run: |
          npm run e2e
        env:
          E2E_ACCESS_TOKEN: '${{ steps.auth.outputs.access_token }}'
          E2E_SOURCE_DOCUMENT_ID: '${{ secrets.E2E_SOURCE_DOCUMENT_ID }}'
